# Generated by Django 3.2.3 on 2021-05-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20210525_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_offer', models.FloatField(null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='shop.auction')),
                ('exchange_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed', to='shop.auction')),
                ('proposal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
