# Generated by Django 3.2.3 on 2021-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
