# Generated by Django 3.2.3 on 2021-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210526_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AlterField(
            model_name='auction',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
