# Generated by Django 3.2.3 on 2021-05-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210526_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.IntegerField(choices=[(1, 'auction'), (2, 'buynow'), (3, 'exchange')], default=1),
            preserve_default=False,
        ),
    ]
